import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ui/darkmode-toggle-button";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className="border-b-2 border-gray-200 flex flex-row justify-between items-center p-4">
                        <Link href="/">
                            {" "}
                            <h1 className=" text-4xl ">News Analysis</h1>
                        </Link>{" "}
                        <div className="flex gap-5 items-center text-2xl">
                          <Link href="/blogs">Blogs</Link>
                        <ModeToggle />
                        </div>
                    </div>
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
